all: \
  Output/Debug/Obj/test_v1\
  Output/Debug/Exe\
  Output/Debug/Exe/test_v1.elf\

Output/Debug/Obj/test_v1:
	mkdir -p "Output/Debug/Obj/test_v1"
Output/Debug/Exe:
	mkdir -p "Output/Debug/Exe"
Output/Debug/Exe/test_v1.elf:\
  Output/Debug/Obj/test_v1/ahrs.o\
  Output/Debug/Obj/test_v1/angle_encoder.o\
  Output/Debug/Obj/test_v1/ctrl_loop.o\
  Output/Debug/Obj/test_v1/esc_ctrl.o\
  Output/Debug/Obj/test_v1/imu.o\
  Output/Debug/Obj/test_v1/kinematics.o\
  Output/Debug/Obj/test_v1/logger.o\
  Output/Debug/Obj/test_v1/svpwm.o\
  Output/Debug/Obj/test_v1/bsp_adc.o\
  Output/Debug/Obj/test_v1/bsp_dma.o\
  Output/Debug/Obj/test_v1/bsp_led.o\
  Output/Debug/Obj/test_v1/bsp_pwm.o\
  Output/Debug/Obj/test_v1/bsp_spi.o\
  Output/Debug/Obj/test_v1/bsp_timer.o\
  Output/Debug/Obj/test_v1/bsp_uart.o\
  Output/Debug/Obj/test_v1/hpm_debug_console.o\
  Output/Debug/Obj/test_v1/system.o\
  Output/Debug/Obj/test_v1/hpm_adc16_drv.o\
  Output/Debug/Obj/test_v1/hpm_dmav2_drv.o\
  Output/Debug/Obj/test_v1/hpm_gpio_drv.o\
  Output/Debug/Obj/test_v1/hpm_gptmr_drv.o\
  Output/Debug/Obj/test_v1/hpm_pcfg_drv.o\
  Output/Debug/Obj/test_v1/hpm_pllctlv2_drv.o\
  Output/Debug/Obj/test_v1/hpm_pwm_drv.o\
  Output/Debug/Obj/test_v1/hpm_spi_drv.o\
  Output/Debug/Obj/test_v1/hpm_uart_drv.o\
  Output/Debug/Obj/test_v1/ctrl.o\
  Output/Debug/Obj/test_v1/fft.o\
  Output/Debug/Obj/test_v1/filter.o\
  Output/Debug/Obj/test_v1/fixed_point.o\
  Output/Debug/Obj/test_v1/misc.o\
  Output/Debug/Obj/test_v1/main.o\
  Output/Debug/Obj/test_v1/hpm_bootheader.o\
  Output/Debug/Obj/test_v1/hpm_clock_drv.o\
  Output/Debug/Obj/test_v1/hpm_l1c_drv.o\
  Output/Debug/Obj/test_v1/hpm_otp_drv.o\
  Output/Debug/Obj/test_v1/hpm_sysctl_drv.o\
  Output/Debug/Obj/test_v1/initfini.o\
  Output/Debug/Obj/test_v1/reset.o\
  Output/Debug/Obj/test_v1/SEGGER_RV32_Startup.o\
  Output/Debug/Obj/test_v1/Startup.o\
  Output/Debug/Obj/test_v1/trap.o\
  G:/UAV_gimbal/program/test_v1/HPM5361/Source/flash_xip.icf\
  G:/UAV_gimbal/program/test_v1/HPM5361/Compenets/nds_dsp/libdspf.a
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/emBuild.exe" "D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/source/riscv_segger_studio_auto.emProject" -config "RV32IMAC Balanced WCHAR32 EnumMinSize Release" -project all -lock "D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/lib/RV32IMAC Balanced WCHAR32 EnumMinSize Release build.lck"

-include Output/Debug/Obj/test_v1/ahrs.d
Output/Debug/Obj/test_v1/ahrs.o:APP/Source/ahrs.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/ahrs.d -MQ Output/Debug/Obj/test_v1/ahrs.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\APP\Source\ahrs.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/ahrs.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/ahrs.asm -o Output/Debug/Obj/test_v1/ahrs.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/ahrs.asm

-include Output/Debug/Obj/test_v1/angle_encoder.d
Output/Debug/Obj/test_v1/angle_encoder.o:APP/Source/angle_encoder.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/angle_encoder.d -MQ Output/Debug/Obj/test_v1/angle_encoder.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\APP\Source\angle_encoder.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/angle_encoder.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/angle_encoder.asm -o Output/Debug/Obj/test_v1/angle_encoder.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/angle_encoder.asm

-include Output/Debug/Obj/test_v1/ctrl_loop.d
Output/Debug/Obj/test_v1/ctrl_loop.o:APP/Source/ctrl_loop.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/ctrl_loop.d -MQ Output/Debug/Obj/test_v1/ctrl_loop.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\APP\Source\ctrl_loop.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/ctrl_loop.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/ctrl_loop.asm -o Output/Debug/Obj/test_v1/ctrl_loop.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/ctrl_loop.asm

-include Output/Debug/Obj/test_v1/esc_ctrl.d
Output/Debug/Obj/test_v1/esc_ctrl.o:APP/Source/esc_ctrl.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/esc_ctrl.d -MQ Output/Debug/Obj/test_v1/esc_ctrl.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\APP\Source\esc_ctrl.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/esc_ctrl.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/esc_ctrl.asm -o Output/Debug/Obj/test_v1/esc_ctrl.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/esc_ctrl.asm

-include Output/Debug/Obj/test_v1/imu.d
Output/Debug/Obj/test_v1/imu.o:APP/Source/imu.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/imu.d -MQ Output/Debug/Obj/test_v1/imu.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\APP\Source\imu.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/imu.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/imu.asm -o Output/Debug/Obj/test_v1/imu.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/imu.asm

-include Output/Debug/Obj/test_v1/kinematics.d
Output/Debug/Obj/test_v1/kinematics.o:APP/Source/kinematics.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/kinematics.d -MQ Output/Debug/Obj/test_v1/kinematics.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\APP\Source\kinematics.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/kinematics.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/kinematics.asm -o Output/Debug/Obj/test_v1/kinematics.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/kinematics.asm

-include Output/Debug/Obj/test_v1/logger.d
Output/Debug/Obj/test_v1/logger.o:APP/Source/logger.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/logger.d -MQ Output/Debug/Obj/test_v1/logger.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\APP\Source\logger.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/logger.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/logger.asm -o Output/Debug/Obj/test_v1/logger.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/logger.asm

-include Output/Debug/Obj/test_v1/svpwm.d
Output/Debug/Obj/test_v1/svpwm.o:APP/Source/svpwm.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/svpwm.d -MQ Output/Debug/Obj/test_v1/svpwm.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\APP\Source\svpwm.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/svpwm.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/svpwm.asm -o Output/Debug/Obj/test_v1/svpwm.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/svpwm.asm

-include Output/Debug/Obj/test_v1/bsp_adc.d
Output/Debug/Obj/test_v1/bsp_adc.o:BSP/Source/bsp_adc.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_adc.d -MQ Output/Debug/Obj/test_v1/bsp_adc.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\BSP\Source\bsp_adc.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_adc.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_adc.asm -o Output/Debug/Obj/test_v1/bsp_adc.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_adc.asm

-include Output/Debug/Obj/test_v1/bsp_dma.d
Output/Debug/Obj/test_v1/bsp_dma.o:BSP/Source/bsp_dma.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_dma.d -MQ Output/Debug/Obj/test_v1/bsp_dma.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\BSP\Source\bsp_dma.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_dma.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_dma.asm -o Output/Debug/Obj/test_v1/bsp_dma.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_dma.asm

-include Output/Debug/Obj/test_v1/bsp_led.d
Output/Debug/Obj/test_v1/bsp_led.o:BSP/Source/bsp_led.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_led.d -MQ Output/Debug/Obj/test_v1/bsp_led.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\BSP\Source\bsp_led.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_led.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_led.asm -o Output/Debug/Obj/test_v1/bsp_led.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_led.asm

-include Output/Debug/Obj/test_v1/bsp_pwm.d
Output/Debug/Obj/test_v1/bsp_pwm.o:BSP/Source/bsp_pwm.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_pwm.d -MQ Output/Debug/Obj/test_v1/bsp_pwm.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\BSP\Source\bsp_pwm.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_pwm.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_pwm.asm -o Output/Debug/Obj/test_v1/bsp_pwm.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_pwm.asm

-include Output/Debug/Obj/test_v1/bsp_spi.d
Output/Debug/Obj/test_v1/bsp_spi.o:BSP/Source/bsp_spi.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_spi.d -MQ Output/Debug/Obj/test_v1/bsp_spi.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\BSP\Source\bsp_spi.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_spi.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_spi.asm -o Output/Debug/Obj/test_v1/bsp_spi.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_spi.asm

-include Output/Debug/Obj/test_v1/bsp_timer.d
Output/Debug/Obj/test_v1/bsp_timer.o:BSP/Source/bsp_timer.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_timer.d -MQ Output/Debug/Obj/test_v1/bsp_timer.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\BSP\Source\bsp_timer.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_timer.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_timer.asm -o Output/Debug/Obj/test_v1/bsp_timer.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_timer.asm

-include Output/Debug/Obj/test_v1/bsp_uart.d
Output/Debug/Obj/test_v1/bsp_uart.o:BSP/Source/bsp_uart.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_uart.d -MQ Output/Debug/Obj/test_v1/bsp_uart.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\BSP\Source\bsp_uart.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_uart.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_uart.asm -o Output/Debug/Obj/test_v1/bsp_uart.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/bsp_uart.asm

-include Output/Debug/Obj/test_v1/hpm_debug_console.d
Output/Debug/Obj/test_v1/hpm_debug_console.o:HPM5361/Compenets/debug_console/hpm_debug_console.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_debug_console.d -MQ Output/Debug/Obj/test_v1/hpm_debug_console.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Compenets\debug_console\hpm_debug_console.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_debug_console.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_debug_console.asm -o Output/Debug/Obj/test_v1/hpm_debug_console.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_debug_console.asm

-include Output/Debug/Obj/test_v1/system.d
Output/Debug/Obj/test_v1/system.o:HPM5361/Device/Source/system.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/system.d -MQ Output/Debug/Obj/test_v1/system.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -mtext=.init -mrodata=.init_rodata -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Device\Source\system.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/system.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/system.asm -o Output/Debug/Obj/test_v1/system.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/system.asm

-include Output/Debug/Obj/test_v1/hpm_adc16_drv.d
Output/Debug/Obj/test_v1/hpm_adc16_drv.o:HPM5361/Device/Source/drivers/hpm_adc16_drv.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_adc16_drv.d -MQ Output/Debug/Obj/test_v1/hpm_adc16_drv.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Device\Source\drivers\hpm_adc16_drv.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_adc16_drv.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_adc16_drv.asm -o Output/Debug/Obj/test_v1/hpm_adc16_drv.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_adc16_drv.asm

-include Output/Debug/Obj/test_v1/hpm_dmav2_drv.d
Output/Debug/Obj/test_v1/hpm_dmav2_drv.o:HPM5361/Device/Source/drivers/hpm_dmav2_drv.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_dmav2_drv.d -MQ Output/Debug/Obj/test_v1/hpm_dmav2_drv.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Device\Source\drivers\hpm_dmav2_drv.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_dmav2_drv.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_dmav2_drv.asm -o Output/Debug/Obj/test_v1/hpm_dmav2_drv.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_dmav2_drv.asm

-include Output/Debug/Obj/test_v1/hpm_gpio_drv.d
Output/Debug/Obj/test_v1/hpm_gpio_drv.o:HPM5361/Device/Source/drivers/hpm_gpio_drv.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_gpio_drv.d -MQ Output/Debug/Obj/test_v1/hpm_gpio_drv.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Device\Source\drivers\hpm_gpio_drv.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_gpio_drv.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_gpio_drv.asm -o Output/Debug/Obj/test_v1/hpm_gpio_drv.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_gpio_drv.asm

-include Output/Debug/Obj/test_v1/hpm_gptmr_drv.d
Output/Debug/Obj/test_v1/hpm_gptmr_drv.o:HPM5361/Device/Source/drivers/hpm_gptmr_drv.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_gptmr_drv.d -MQ Output/Debug/Obj/test_v1/hpm_gptmr_drv.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Device\Source\drivers\hpm_gptmr_drv.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_gptmr_drv.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_gptmr_drv.asm -o Output/Debug/Obj/test_v1/hpm_gptmr_drv.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_gptmr_drv.asm

-include Output/Debug/Obj/test_v1/hpm_pcfg_drv.d
Output/Debug/Obj/test_v1/hpm_pcfg_drv.o:HPM5361/Device/Source/drivers/hpm_pcfg_drv.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_pcfg_drv.d -MQ Output/Debug/Obj/test_v1/hpm_pcfg_drv.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Device\Source\drivers\hpm_pcfg_drv.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_pcfg_drv.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_pcfg_drv.asm -o Output/Debug/Obj/test_v1/hpm_pcfg_drv.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_pcfg_drv.asm

-include Output/Debug/Obj/test_v1/hpm_pllctlv2_drv.d
Output/Debug/Obj/test_v1/hpm_pllctlv2_drv.o:HPM5361/Device/Source/drivers/hpm_pllctlv2_drv.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_pllctlv2_drv.d -MQ Output/Debug/Obj/test_v1/hpm_pllctlv2_drv.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Device\Source\drivers\hpm_pllctlv2_drv.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_pllctlv2_drv.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_pllctlv2_drv.asm -o Output/Debug/Obj/test_v1/hpm_pllctlv2_drv.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_pllctlv2_drv.asm

-include Output/Debug/Obj/test_v1/hpm_pwm_drv.d
Output/Debug/Obj/test_v1/hpm_pwm_drv.o:HPM5361/Device/Source/drivers/hpm_pwm_drv.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_pwm_drv.d -MQ Output/Debug/Obj/test_v1/hpm_pwm_drv.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Device\Source\drivers\hpm_pwm_drv.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_pwm_drv.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_pwm_drv.asm -o Output/Debug/Obj/test_v1/hpm_pwm_drv.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_pwm_drv.asm

-include Output/Debug/Obj/test_v1/hpm_spi_drv.d
Output/Debug/Obj/test_v1/hpm_spi_drv.o:HPM5361/Device/Source/drivers/hpm_spi_drv.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_spi_drv.d -MQ Output/Debug/Obj/test_v1/hpm_spi_drv.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Device\Source\drivers\hpm_spi_drv.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_spi_drv.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_spi_drv.asm -o Output/Debug/Obj/test_v1/hpm_spi_drv.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_spi_drv.asm

-include Output/Debug/Obj/test_v1/hpm_uart_drv.d
Output/Debug/Obj/test_v1/hpm_uart_drv.o:HPM5361/Device/Source/drivers/hpm_uart_drv.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_uart_drv.d -MQ Output/Debug/Obj/test_v1/hpm_uart_drv.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Device\Source\drivers\hpm_uart_drv.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_uart_drv.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_uart_drv.asm -o Output/Debug/Obj/test_v1/hpm_uart_drv.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_uart_drv.asm

-include Output/Debug/Obj/test_v1/ctrl.d
Output/Debug/Obj/test_v1/ctrl.o:MISC/Source/ctrl.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/ctrl.d -MQ Output/Debug/Obj/test_v1/ctrl.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\MISC\Source\ctrl.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/ctrl.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/ctrl.asm -o Output/Debug/Obj/test_v1/ctrl.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/ctrl.asm

-include Output/Debug/Obj/test_v1/fft.d
Output/Debug/Obj/test_v1/fft.o:MISC/Source/fft.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/fft.d -MQ Output/Debug/Obj/test_v1/fft.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\MISC\Source\fft.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/fft.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/fft.asm -o Output/Debug/Obj/test_v1/fft.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/fft.asm

-include Output/Debug/Obj/test_v1/filter.d
Output/Debug/Obj/test_v1/filter.o:MISC/Source/filter.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/filter.d -MQ Output/Debug/Obj/test_v1/filter.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\MISC\Source\filter.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/filter.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/filter.asm -o Output/Debug/Obj/test_v1/filter.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/filter.asm

-include Output/Debug/Obj/test_v1/fixed_point.d
Output/Debug/Obj/test_v1/fixed_point.o:MISC/Source/fixed_point.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/fixed_point.d -MQ Output/Debug/Obj/test_v1/fixed_point.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\MISC\Source\fixed_point.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/fixed_point.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/fixed_point.asm -o Output/Debug/Obj/test_v1/fixed_point.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/fixed_point.asm

-include Output/Debug/Obj/test_v1/misc.d
Output/Debug/Obj/test_v1/misc.o:MISC/Source/misc.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/misc.d -MQ Output/Debug/Obj/test_v1/misc.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\MISC\Source\misc.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/misc.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/misc.asm -o Output/Debug/Obj/test_v1/misc.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/misc.asm

-include Output/Debug/Obj/test_v1/main.d
Output/Debug/Obj/test_v1/main.o:main.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/main.d -MQ Output/Debug/Obj/test_v1/main.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\main.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/main.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/main.asm -o Output/Debug/Obj/test_v1/main.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/main.asm

-include Output/Debug/Obj/test_v1/hpm_bootheader.d
Output/Debug/Obj/test_v1/hpm_bootheader.o:HPM5361/Device/Source/hpm_bootheader.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_bootheader.d -MQ Output/Debug/Obj/test_v1/hpm_bootheader.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Device\Source\hpm_bootheader.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_bootheader.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_bootheader.asm -o Output/Debug/Obj/test_v1/hpm_bootheader.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_bootheader.asm

-include Output/Debug/Obj/test_v1/hpm_clock_drv.d
Output/Debug/Obj/test_v1/hpm_clock_drv.o:HPM5361/Device/Source/hpm_clock_drv.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_clock_drv.d -MQ Output/Debug/Obj/test_v1/hpm_clock_drv.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Device\Source\hpm_clock_drv.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_clock_drv.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_clock_drv.asm -o Output/Debug/Obj/test_v1/hpm_clock_drv.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_clock_drv.asm

-include Output/Debug/Obj/test_v1/hpm_l1c_drv.d
Output/Debug/Obj/test_v1/hpm_l1c_drv.o:HPM5361/Device/Source/hpm_l1c_drv.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_l1c_drv.d -MQ Output/Debug/Obj/test_v1/hpm_l1c_drv.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Device\Source\hpm_l1c_drv.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_l1c_drv.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_l1c_drv.asm -o Output/Debug/Obj/test_v1/hpm_l1c_drv.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_l1c_drv.asm

-include Output/Debug/Obj/test_v1/hpm_otp_drv.d
Output/Debug/Obj/test_v1/hpm_otp_drv.o:HPM5361/Device/Source/hpm_otp_drv.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_otp_drv.d -MQ Output/Debug/Obj/test_v1/hpm_otp_drv.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Device\Source\hpm_otp_drv.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_otp_drv.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_otp_drv.asm -o Output/Debug/Obj/test_v1/hpm_otp_drv.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_otp_drv.asm

-include Output/Debug/Obj/test_v1/hpm_sysctl_drv.d
Output/Debug/Obj/test_v1/hpm_sysctl_drv.o:HPM5361/Device/Source/hpm_sysctl_drv.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_sysctl_drv.d -MQ Output/Debug/Obj/test_v1/hpm_sysctl_drv.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Device\Source\hpm_sysctl_drv.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_sysctl_drv.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_sysctl_drv.asm -o Output/Debug/Obj/test_v1/hpm_sysctl_drv.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/hpm_sysctl_drv.asm

-include Output/Debug/Obj/test_v1/initfini.d
Output/Debug/Obj/test_v1/initfini.o:HPM5361/Device/Source/initfini.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/initfini.d -MQ Output/Debug/Obj/test_v1/initfini.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Device\Source\initfini.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/initfini.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/initfini.asm -o Output/Debug/Obj/test_v1/initfini.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/initfini.asm

-include Output/Debug/Obj/test_v1/reset.d
Output/Debug/Obj/test_v1/reset.o:HPM5361/Device/Source/reset.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/reset.d -MQ Output/Debug/Obj/test_v1/reset.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Device\Source\reset.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/reset.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/reset.asm -o Output/Debug/Obj/test_v1/reset.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/reset.asm

-include Output/Debug/Obj/test_v1/SEGGER_RV32_Startup.d
Output/Debug/Obj/test_v1/SEGGER_RV32_Startup.o:HPM5361/Source/SEGGER_RV32_Startup.s
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -lang-asm -fdiagnostics-color=never -fdiagnostics-show-caret -E -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/SEGGER_RV32_Startup.d -MQ Output/Debug/Obj/test_v1/SEGGER_RV32_Startup.o -quiet G:\UAV_gimbal\program\test_v1\HPM5361\Source\SEGGER_RV32_Startup.s -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/SEGGER_RV32_Startup_PP.s
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/SEGGER_RV32_Startup_PP.s -o Output/Debug/Obj/test_v1/SEGGER_RV32_Startup.o -g -gdwarf-4
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/SEGGER_RV32_Startup_PP.s

-include Output/Debug/Obj/test_v1/Startup.d
Output/Debug/Obj/test_v1/Startup.o:HPM5361/Source/Startup.s
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -lang-asm -fdiagnostics-color=never -fdiagnostics-show-caret -E -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/Startup.d -MQ Output/Debug/Obj/test_v1/Startup.o -quiet G:\UAV_gimbal\program\test_v1\HPM5361\Source\Startup.s -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/Startup_PP.s
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/Startup_PP.s -o Output/Debug/Obj/test_v1/Startup.o -g -gdwarf-4
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/Startup_PP.s

-include Output/Debug/Obj/test_v1/trap.d
Output/Debug/Obj/test_v1/trap.o:HPM5361/Device/Source/trap.c
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/cc1.exe" -fmessage-length=0 -fdiagnostics-color=never -fdiagnostics-show-caret -std=gnu99 -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax -nostdinc "-isystemD:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/include" -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -D__SES_RISCV -D__SEGGER_LINKER -D__HEAP_SIZE__=16384 -D__SES_VERSION=81601 -DDEBUG -DHPM5361xCFx -D__HPM5361XCFX_SUBFAMILY -D__HPM5361_FAMILY -DFLASH_XIP=1 -MD G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/trap.d -MQ Output/Debug/Obj/test_v1/trap.o -quiet -gdwarf-4 -g3 -gpubnames -fomit-frame-pointer -ffunction-sections -fdata-sections -fshort-enums -fno-signed-char -fno-common G:\UAV_gimbal\program\test_v1\HPM5361\Device\Source\trap.c -o G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/trap.asm -Wuninitialized
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/as.exe" --traditional-format -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Device/Include/riscv -IG:/UAV_gimbal/program/test_v1/BSP/Include -IG:/UAV_gimbal/program/test_v1/APP/Include -IG:/UAV_gimbal/program/test_v1/MISC/Include -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets -IG:/UAV_gimbal/program/test_v1/HPM5361/Compenets/debug_console -march=rv32imac_zicsr_zifencei_zba_zbb_zbc_zbs -mabi=ilp32f -mrelax G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/trap.asm -o Output/Debug/Obj/test_v1/trap.o
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/rm.exe" -f G:/UAV_gimbal/program/test_v1/Output/Debug/Obj/test_v1/trap.asm

Output/Debug/Exe/test_v1.elf:\
  Output/Debug/Obj/test_v1/ahrs.o\
  Output/Debug/Obj/test_v1/angle_encoder.o\
  Output/Debug/Obj/test_v1/ctrl_loop.o\
  Output/Debug/Obj/test_v1/esc_ctrl.o\
  Output/Debug/Obj/test_v1/imu.o\
  Output/Debug/Obj/test_v1/kinematics.o\
  Output/Debug/Obj/test_v1/logger.o\
  Output/Debug/Obj/test_v1/svpwm.o\
  Output/Debug/Obj/test_v1/bsp_adc.o\
  Output/Debug/Obj/test_v1/bsp_dma.o\
  Output/Debug/Obj/test_v1/bsp_led.o\
  Output/Debug/Obj/test_v1/bsp_pwm.o\
  Output/Debug/Obj/test_v1/bsp_spi.o\
  Output/Debug/Obj/test_v1/bsp_timer.o\
  Output/Debug/Obj/test_v1/bsp_uart.o\
  Output/Debug/Obj/test_v1/hpm_debug_console.o\
  Output/Debug/Obj/test_v1/system.o\
  Output/Debug/Obj/test_v1/hpm_adc16_drv.o\
  Output/Debug/Obj/test_v1/hpm_dmav2_drv.o\
  Output/Debug/Obj/test_v1/hpm_gpio_drv.o\
  Output/Debug/Obj/test_v1/hpm_gptmr_drv.o\
  Output/Debug/Obj/test_v1/hpm_pcfg_drv.o\
  Output/Debug/Obj/test_v1/hpm_pllctlv2_drv.o\
  Output/Debug/Obj/test_v1/hpm_pwm_drv.o\
  Output/Debug/Obj/test_v1/hpm_spi_drv.o\
  Output/Debug/Obj/test_v1/hpm_uart_drv.o\
  Output/Debug/Obj/test_v1/ctrl.o\
  Output/Debug/Obj/test_v1/fft.o\
  Output/Debug/Obj/test_v1/filter.o\
  Output/Debug/Obj/test_v1/fixed_point.o\
  Output/Debug/Obj/test_v1/misc.o\
  Output/Debug/Obj/test_v1/main.o\
  Output/Debug/Obj/test_v1/hpm_bootheader.o\
  Output/Debug/Obj/test_v1/hpm_clock_drv.o\
  Output/Debug/Obj/test_v1/hpm_l1c_drv.o\
  Output/Debug/Obj/test_v1/hpm_otp_drv.o\
  Output/Debug/Obj/test_v1/hpm_sysctl_drv.o\
  Output/Debug/Obj/test_v1/initfini.o\
  Output/Debug/Obj/test_v1/reset.o\
  Output/Debug/Obj/test_v1/SEGGER_RV32_Startup.o\
  Output/Debug/Obj/test_v1/Startup.o\
  Output/Debug/Obj/test_v1/trap.o\
  G:/UAV_gimbal/program/test_v1/HPM5361/Source/flash_xip.icf\
  G:/UAV_gimbal/program/test_v1/HPM5361/Compenets/nds_dsp/libdspf.a
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/bin/segger-ld.exe" --full-section-headers --merge-sections --merge-strings --map-text --map-file=Output/Debug/Exe/test_v1.map --map-standard -eReset_Handler -mcpu=rv32imac --no-outline --relax --no-springboard --no-tail-merge --tp-model=auto --silent --list-all-undefineds -TG:/UAV_gimbal/program/test_v1/HPM5361/Source/flash_xip.icf --defsym=__STACKSIZE__=16384 --defsym=__HEAPSIZE__=16384 --defsym=__SEGGER_RTL_vfprintf=__SEGGER_RTL_vfprintf_int_nwp --defsym=__SEGGER_RTL_vfscanf=__SEGGER_RTL_vfscanf_int -o G:/UAV_gimbal/program/test_v1/Output/Debug/Exe/test_v1.elf Output/Debug/Obj/test_v1/ahrs.o Output/Debug/Obj/test_v1/angle_encoder.o Output/Debug/Obj/test_v1/ctrl_loop.o Output/Debug/Obj/test_v1/esc_ctrl.o Output/Debug/Obj/test_v1/imu.o Output/Debug/Obj/test_v1/kinematics.o Output/Debug/Obj/test_v1/logger.o Output/Debug/Obj/test_v1/svpwm.o Output/Debug/Obj/test_v1/bsp_adc.o Output/Debug/Obj/test_v1/bsp_dma.o Output/Debug/Obj/test_v1/bsp_led.o Output/Debug/Obj/test_v1/bsp_pwm.o Output/Debug/Obj/test_v1/bsp_spi.o Output/Debug/Obj/test_v1/bsp_timer.o Output/Debug/Obj/test_v1/bsp_uart.o Output/Debug/Obj/test_v1/hpm_debug_console.o Output/Debug/Obj/test_v1/system.o Output/Debug/Obj/test_v1/hpm_adc16_drv.o Output/Debug/Obj/test_v1/hpm_dmav2_drv.o Output/Debug/Obj/test_v1/hpm_gpio_drv.o Output/Debug/Obj/test_v1/hpm_gptmr_drv.o Output/Debug/Obj/test_v1/hpm_pcfg_drv.o Output/Debug/Obj/test_v1/hpm_pllctlv2_drv.o Output/Debug/Obj/test_v1/hpm_pwm_drv.o Output/Debug/Obj/test_v1/hpm_spi_drv.o Output/Debug/Obj/test_v1/hpm_uart_drv.o Output/Debug/Obj/test_v1/ctrl.o Output/Debug/Obj/test_v1/fft.o Output/Debug/Obj/test_v1/filter.o Output/Debug/Obj/test_v1/fixed_point.o Output/Debug/Obj/test_v1/misc.o Output/Debug/Obj/test_v1/main.o Output/Debug/Obj/test_v1/hpm_bootheader.o Output/Debug/Obj/test_v1/hpm_clock_drv.o Output/Debug/Obj/test_v1/hpm_l1c_drv.o Output/Debug/Obj/test_v1/hpm_otp_drv.o Output/Debug/Obj/test_v1/hpm_sysctl_drv.o Output/Debug/Obj/test_v1/initfini.o Output/Debug/Obj/test_v1/reset.o Output/Debug/Obj/test_v1/SEGGER_RV32_Startup.o Output/Debug/Obj/test_v1/Startup.o Output/Debug/Obj/test_v1/trap.o G:/UAV_gimbal/program/test_v1/HPM5361/Compenets/nds_dsp/libdspf.a "D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/lib/libc_rv32imac_f_balanced.a" "D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a//SEGGER_RV32_crtinit_rv32imac_f_balanced.a" "D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/lib/prinops_semihost_rv32imac_f_balanced.a" "D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/lib/prinops_semihostformatted_rv32imac_f_balanced.a" "D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/lib/heapops_basic_rv32imac_f_balanced.a" "D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/lib/heapops_disable_interrupts_locking_rv32imac_f_balanced.a" "D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/lib/mbops_timeops_rv32imac_f_balanced.a"
	"D:/Program Files/SEGGER/SEGGER Embedded Studio 8.16a/gcc/riscv32-none-elf/bin/objcopy.exe" Output/Debug/Exe/test_v1.elf G:/UAV_gimbal/program/test_v1/Output/Debug/Exe/test_v1.bin -Obinary